name: Build & Push

on:
  workflow_dispatch: 
  push:
    branches:
      - test 

jobs:
  build-and-push:
    runs-on: self-hosted 

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Construir y subir imagen a Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: carlasanmartiniglesias/carla.sanmartin.iglesias-daw-web:latest

      - name: Desplegar imagen en el runner
        run: |
          if [ "$(docker ps -aq -f name=daw-web)" ]; then
            docker stop daw-web
            docker rm daw-web
          fi
          docker run -d --name daw-web -p 8888:80 carlasanmartiniglesias/carla.sanmartin.iglesias-daw-web:latest
